name: Replace IP Address
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "request.environ.get('HTTP_X_FORWARDED_FOR', request.remote_addr)"
          replace: "requests.get('https://ipinfo.io/ip').text"
          include: "app.py"
          regex: false
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
