name: Replace IP Address
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "request.environ.get('HTTP_X_FORWARDED_FOR', request.remote_addr)"
          replace: "requests.get('https://ipinfo.io/ip').text"
          regex: false
